name: Mon premier Worflow
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "Hello Shantou"
        - uses: actions/checkout@v4
        - name: set up JDK 11
          uses: actions/setup-java@v4
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
        - name: Build with gradle
          uses: ./gradlew build
    
  
