name: Mon premier Worflow
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout
          uses: actions/checkout@v5.0.0        
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
        - name: Build with gradle
          uses: ./gradlew build
    
  
